version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: eventflow_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demetrio08
      POSTGRES_DB: eventflow_db
    ports:
      - "5432:5432"
    networks:
      - eventflow-net
    volumes:
      - eventflow_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eventflow.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - eventflow-net

networks:
  eventflow-net:

volumes:
  eventflow_data:
