services:
  postgres:
    image: postgres:15
    container_name: eventflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demetrio08
      POSTGRES_DB: eventflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventflow-network

volumes:
  postgres_data:

networks:
  eventflow-network:
    driver: bridge
